export default [
{ abbr: "ACDT", id: "Australian Central Daylight Savings Time", UTC: "10:30" },
{ abbr: "ACST", id: "Australian Central Standard Time", UTC: "09:30" },
{ abbr: "ACT", id: "Acre Time", UTC: -05 },
// { abbr: "ACT", id: "ASEAN Common Time", UTC: "06:30 – UTC09" },
{ abbr: "ACWST", id: "Australian Central Western Standard Time (unofficial)", UTC: "08:45" },
{ abbr: "ADT", id: "Atlantic Daylight Time", UTC: -03 },
{ abbr: "AEDT", id: "Australian Eastern Daylight Savings Time", UTC: 11 },
{ abbr: "AEST", id: "Australian Eastern Standard Time", UTC: 10 },
{ abbr: "AFT", id: "Afghanistan Time", UTC: "04:30" },
{ abbr: "AKDT", id: "Alaska Daylight Time", UTC: -08 },
{ abbr: "AKST", id: "Alaska Standard Time", UTC: -09 },
{ abbr: "AMST", id: "Amazon Summer Time (Brazil)[1]", UTC: -03 },
{ abbr: "AMT", id: "Amazon Time (Brazil)[2]", UTC: -04 },
{ abbr: "AMT", id: "Armenia Time", UTC: 04 },
{ abbr: "ART", id: "Argentina Time", UTC: -03 },
{ abbr: "AST", id: "Arabia Standard Time", UTC: 03 },
{ abbr: "AST", id: "Atlantic Standard Time", UTC: -04 },
{ abbr: "AWST", id: "Australian Western Standard Time", UTC: 08 },
{ abbr: "AZOST", id: "Azores Summer Time", UTC: -00 },
{ abbr: "AZOT", id: "Azores Standard Time", UTC: -01 },
{ abbr: "AZT", id: "Azerbaijan Time", UTC: 04 },
{ abbr: "BDT", id: "Brunei Time", UTC: 08 },
{ abbr: "BIOT", id: "British Indian Ocean Time", UTC: 06 },
{ abbr: "BIT", id: "Baker Island Time", UTC: -12 },
{ abbr: "BOT", id: "Bolivia Time", UTC: -04 },
{ abbr: "BRST", id: "Brasília Summer Time", UTC: -02 },
{ abbr: "BRT", id: "Brasilia Time", UTC: -03 },
{ abbr: "BST", id: "Bangladesh Standard Time", UTC: 06 },
{ abbr: "BST", id: "Bougainville Standard Time[3]", UTC: 11 },
// { abbr: "BST", id: "British Summer Time (British Standard Time from Feb 1968 to Oct 1971)", UTC: 01 },
{ abbr: "BTT", id: "Bhutan Time", UTC: 06 },
{ abbr: "CAT", id: "Central Africa Time", UTC: 02 },
{ abbr: "CCT", id: "Cocos Islands Time", UTC: "06:30" },
{ abbr: "CDT", id: "Central Daylight Time (North America)", UTC: -05 },
{ abbr: "CDT", id: "Cuba Daylight Time[4]", UTC: -04 },
{ abbr: "CEST", id: "Central European Summer Time (Cf. HAEC)", UTC: 02 },
{ abbr: "CET", id: "Central European Time", UTC: 01 },
{ abbr: "CHADT", id: "Chatham Daylight Time", UTC: "13:45" },
{ abbr: "CHAST", id: "Chatham Standard Time", UTC: "12:45" },
{ abbr: "CHOT", id: "Choibalsan Standard Time", UTC: 08 },
{ abbr: "CHOST", id: "Choibalsan Summer Time", UTC: 09 },
{ abbr: "CHST", id: "Chamorro Standard Time", UTC: 10 },
{ abbr: "CHUT", id: "Chuuk Time", UTC: 10 },
{ abbr: "CIST", id: "Clipperton Island Standard Time", UTC: -08 },
{ abbr: "CIT", id: "Central Indonesia Time", UTC: 08 },
{ abbr: "CKT", id: "Cook Island Time", UTC: -10 },
{ abbr: "CLST", id: "Chile Summer Time", UTC: -03 },
{ abbr: "CLT", id: "Chile Standard Time", UTC: -04 },
{ abbr: "COST", id: "Colombia Summer Time", UTC: -04 },
{ abbr: "COT", id: "Colombia Time", UTC: -05 },
{ abbr: "CST", id: "Central Standard Time (North America)", UTC: -06 },
{ abbr: "CST", id: "China Standard Time", UTC: 08 },
{ abbr: "CST", id: "Cuba Standard Time", UTC: -05 },
{ abbr: "CT", id: "China Time", UTC: 08 },
{ abbr: "CVT", id: "Cape Verde Time", UTC: -01 },
{ abbr: "CWST", id: "Central Western Standard Time (Australia) unofficial", UTC: "08:45" },
{ abbr: "CXT", id: "Christmas Island Time", UTC: 07 },
{ abbr: "DAVT", id: "Davis Time", UTC: 07 },
{ abbr: "DDUT", id: "Dumont d'Urville Time", UTC: 10 },
{ abbr: "DFT", id: "AIX-specific equivalent of Central European Time[NB 1]", UTC: 01 },
{ abbr: "EASST", id: "Easter Island Summer Time", UTC: -05 },
{ abbr: "EAST", id: "Easter Island Standard Time", UTC: -06 },
{ abbr: "EAT", id: "East Africa Time", UTC: 03 },
{ abbr: "ECT", id: "Eastern Caribbean Time (does not recognise DST)", UTC: -04 },
{ abbr: "ECT", id: "Ecuador Time", UTC: -05 },
{ abbr: "EDT", id: "Eastern Daylight Time (North America)", UTC: -04 },
{ abbr: "EEST", id: "Eastern European Summer Time", UTC: 03 },
{ abbr: "EET", id: "Eastern European Time", UTC: 02 },
{ abbr: "EGST", id: "Eastern Greenland Summer Time", UTC: "±00" },
{ abbr: "EGT", id: "Eastern Greenland Time", UTC: -01 },
{ abbr: "EIT", id: "Eastern Indonesian Time", UTC: 09 },
{ abbr: "EST", id: "Eastern Standard Time (North America)", UTC: -05 },
{ abbr: "FET", id: "Further-eastern European Time", UTC: 03 },
{ abbr: "FJT", id: "Fiji Time", UTC: 12 },
{ abbr: "FKST", id: "Falkland Islands Summer Time", UTC: -03 },
{ abbr: "FKT", id: "Falkland Islands Time", UTC: -04 },
{ abbr: "FNT", id: "Fernando de Noronha Time", UTC: -02 },
{ abbr: "GALT", id: "Galápagos Time", UTC: -06 },
{ abbr: "GAMT", id: "Gambier Islands Time", UTC: -09 },
{ abbr: "GET", id: "Georgia Standard Time", UTC: 04 },
{ abbr: "GFT", id: "French Guiana Time", UTC: -03 },
{ abbr: "GILT", id: "Gilbert Island Time", UTC: 12 },
{ abbr: "GIT", id: "Gambier Island Time", UTC: -09 },
{ abbr: "GMT", id: "Greenwich Mean Time", UTC: "±00" },
{ abbr: "GST", id: "South Georgia and the South Sandwich Islands Time", UTC: -02 },
{ abbr: "GST", id: "Gulf Standard Time", UTC: 04 },
{ abbr: "GYT", id: "Guyana Time", UTC: -04 },
{ abbr: "HDT", id: "Hawaii–Aleutian Daylight Time", UTC: -09 },
{ abbr: "HAEC", id: "Heure Avancée d'Europe Centrale French-language name for CEST", UTC: 02 },
{ abbr: "HST", id: "Hawaii–Aleutian Standard Time", UTC: -10 },
{ abbr: "HKT", id: "Hong Kong Time", UTC: 08 },
{ abbr: "HMT", id: "Heard and McDonald Islands Time", UTC: 05 },
{ abbr: "HOVST", id: "Khovd Summer Time", UTC: 08 },
{ abbr: "HOVT", id: "Khovd Standard Time", UTC: 07 },
{ abbr: "ICT", id: "Indochina Time", UTC: 07 },
{ abbr: "IDT", id: "Israel Daylight Time", UTC: 03 },
{ abbr: "IOT", id: "Indian Ocean Time", UTC: 03 },
{ abbr: "IRDT", id: "Iran Daylight Time", UTC: "04:30" },
{ abbr: "IRKT", id: "Irkutsk Time", UTC: 08 },
{ abbr: "IRST", id: "Iran Standard Time", UTC: "03:30" },
{ abbr: "IST", id: "Indian Standard Time", UTC: "05:30" },
{ abbr: "IST", id: "Irish Standard Time[5]", UTC: 01 },
{ abbr: "IST", id: "Israel Standard Time", UTC: 02 },
{ abbr: "JST", id: "Japan Standard Time", UTC: 09 },
{ abbr: "KGT", id: "Kyrgyzstan Time", UTC: 06 },
{ abbr: "KOST", id: "Kosrae Time", UTC: 11 },
{ abbr: "KRAT", id: "Krasnoyarsk Time", UTC: 07 },
{ abbr: "KST", id: "Korea Standard Time", UTC: 09 },
{ abbr: "LHST", id: "Lord Howe Standard Time", UTC: "10:30" },
{ abbr: "LHST", id: "Lord Howe Summer Time", UTC: 11 },
{ abbr: "LINT", id: "Line Islands Time", UTC: 14 },
{ abbr: "MAGT", id: "Magadan Time", UTC: 12 },
{ abbr: "MART", id: "Marquesas Islands Time", UTC: "-09:30" },
{ abbr: "MAWT", id: "Mawson Station Time", UTC: 05 },
{ abbr: "MDT", id: "Mountain Daylight Time (North America)", UTC: -06 },
{ abbr: "MET", id: "Middle European Time Same zone as CET", UTC: 01 },
{ abbr: "MEST", id: "Middle European Summer Time Same zone as CEST", UTC: 02 },
{ abbr: "MHT", id: "Marshall Islands Time", UTC: 12 },
{ abbr: "MIST", id: "Macquarie Island Station Time", UTC: 11 },
{ abbr: "MIT", id: "Marquesas Islands Time", UTC: "-09:30" },
{ abbr: "MMT", id: "Myanmar Standard Time", UTC: "06:30" },
{ abbr: "MSK", id: "Moscow Time", UTC: 03 },
{ abbr: "MST", id: "Malaysia Standard Time", UTC: 08 },
{ abbr: "MST", id: "Mountain Standard Time (North America)", UTC: -07 },
{ abbr: "MUT", id: "Mauritius Time", UTC: 04 },
{ abbr: "MVT", id: "Maldives Time", UTC: 05 },
{ abbr: "MYT", id: "Malaysia Time", UTC: 08 },
{ abbr: "NCT", id: "New Caledonia Time", UTC: 11 },
{ abbr: "NDT", id: "Newfoundland Daylight Time", UTC: "-02:30" },
{ abbr: "NFT", id: "Norfolk Island Time", UTC: 11 },
{ abbr: "NPT", id: "Nepal Time", UTC: "05:45" },
{ abbr: "NST", id: "Newfoundland Standard Time", UTC: "-03:30" },
{ abbr: "NT", id: "Newfoundland Time", UTC: "-03:30" },
{ abbr: "NUT", id: "Niue Time", UTC: -11 },
{ abbr: "NZDT", id: "New Zealand Daylight Time", UTC: 13 },
{ abbr: "NZST", id: "New Zealand Standard Time", UTC: 12 },
{ abbr: "OMST", id: "Omsk Time", UTC: 06 },
{ abbr: "ORAT", id: "Oral Time", UTC: 05 },
{ abbr: "PDT", id: "Pacific Daylight Time (North America)", UTC: -07 },
{ abbr: "PET", id: "Peru Time", UTC: -05 },
{ abbr: "PETT", id: "Kamchatka Time", UTC: 12 },
{ abbr: "PGT", id: "Papua New Guinea Time", UTC: 10 },
{ abbr: "PHOT", id: "Phoenix Island Time", UTC: 13 },
{ abbr: "PHT", id: "Philippine Time", UTC: 08 },
{ abbr: "PKT", id: "Pakistan Standard Time", UTC: 05 },
{ abbr: "PMDT", id: "Saint Pierre and Miquelon Daylight Time", UTC: -02 },
{ abbr: "PMST", id: "Saint Pierre and Miquelon Standard Time", UTC: -03 },
{ abbr: "PONT", id: "Pohnpei Standard Time", UTC: 11 },
{ abbr: "PST", id: "Pacific Standard Time (North America)", UTC: -08 },
{ abbr: "PST", id: "Philippine Standard Time", UTC: 08 },
{ abbr: "PYST", id: "Paraguay Summer Time[6]", UTC: -03 },
{ abbr: "PYT", id: "Paraguay Time[7]", UTC: -04 },
{ abbr: "RET", id: "Réunion Time", UTC: 04 },
{ abbr: "ROTT", id: "Rothera Research Station Time", UTC: -03 },
{ abbr: "SAKT", id: "Sakhalin Island Time", UTC: 11 },
{ abbr: "SAMT", id: "Samara Time", UTC: 04 },
{ abbr: "SAST", id: "South African Standard Time", UTC: 02 },
{ abbr: "SBT", id: "Solomon Islands Time", UTC: 11 },
{ abbr: "SCT", id: "Seychelles Time", UTC: 04 },
{ abbr: "SDT", id: "Samoa Daylight Time", UTC: -10 },
{ abbr: "SGT", id: "Singapore Time", UTC: 08 },
{ abbr: "SLST", id: "Sri Lanka Standard Time", UTC: "05:30" },
{ abbr: "SRET", id: "Srednekolymsk Time", UTC: 11 },
{ abbr: "SRT", id: "Suriname Time", UTC: -03 },
{ abbr: "SST", id: "Samoa Standard Time", UTC: -11 },
{ abbr: "SST", id: "Singapore Standard Time", UTC: 08 },
{ abbr: "SYOT", id: "Showa Station Time", UTC: 03 },
{ abbr: "TAHT", id: "Tahiti Time", UTC: -10 },
{ abbr: "THA", id: "Thailand Standard Time", UTC: 07 },
{ abbr: "TFT", id: "Indian/Kerguelen", UTC: 05 },
{ abbr: "TJT", id: "Tajikistan Time", UTC: 05 },
{ abbr: "TKT", id: "Tokelau Time", UTC: 13 },
{ abbr: "TLT", id: "Timor Leste Time", UTC: 09 },
{ abbr: "TMT", id: "Turkmenistan Time", UTC: 05 },
{ abbr: "TRT", id: "Turkey Time", UTC: 03 },
{ abbr: "TOT", id: "Tonga Time", UTC: 13 },
{ abbr: "TVT", id: "Tuvalu Time", UTC: 12 },
{ abbr: "ULAST", id: "Ulaanbaatar Summer Time", UTC: 09 },
{ abbr: "ULAT", id: "Ulaanbaatar Standard Time", UTC: 08 },
{ abbr: "USZ1", id: "Kaliningrad Time", UTC: 02 },
{ abbr: UTC, id: "Coordinated Universal Time", UTC: "±00" },
{ abbr: "UYST", id: "Uruguay Summer Time", UTC: -02 },
{ abbr: "UYT", id: "Uruguay Standard Time", UTC: -03 },
{ abbr: "UZT", id: "Uzbekistan Time", UTC: 05 },
{ abbr: "VET", id: "Venezuelan Standard Time", UTC: -04 },
{ abbr: "VLAT", id: "Vladivostok Time", UTC: 10 },
{ abbr: "VOLT", id: "Volgograd Time", UTC: 04 },
{ abbr: "VOST", id: "Vostok Station Time", UTC: 06 },
{ abbr: "VUT", id: "Vanuatu Time", UTC: 11 },
{ abbr: "WAKT", id: "Wake Island Time", UTC: 12 },
{ abbr: "WAST", id: "West Africa Summer Time", UTC: 02 },
{ abbr: "WAT", id: "West Africa Time", UTC: 01 },
{ abbr: "WEST", id: "Western European Summer Time", UTC: 01 },
{ abbr: "WET", id: "Western European Time", UTC: "±00" },
{ abbr: "WIT", id: "Western Indonesian Time", UTC: 07 },
{ abbr: "WST", id: "Western Standard Time", UTC: 08 },
{ abbr: "YAKT", id: "Yakutsk Time", UTC: 09 },
{ abbr: "YEKT", id: "Yekaterinburg Time", UTC: 05 }
];